# Generated by Django 4.0.6 on 2022-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_scrapper', '0002_channelwiselastsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(default=None),
        ),
    ]
